import { useState, type ReactNode } from 'react';
import type { State, Scene, Character, WorldFact, Save } from './types';
import {MotivationEditor} from './MotivationEditor';
import {RelationshipEditor} from './RelationshipEditor';
import { Markdown } from './Markdown';
export const brief = (text: string, n = 150) => { const clean = text.replace(/[#*_`>]/g, '').replace(/\s+/g, ' ').trim(); return clean.length > n ? clean.slice(0, n).replace(/\s+\S*$/, '') + '…' : clean; };
const nameOf = (s: State, id: string) => s.characters.find(c => c.id === id)?.name || id;
const names = (s: State, ids: string[]) => ids.map(id => nameOf(s, id)).join(', ') || 'Не указаны';
const stamp = (minute: number | null) => minute == null ? 'Время не указано' : `День ${Math.floor(minute / 1440) + 1} (${'Пн Вт Ср Чт Пт Сб Вс'.split(' ')[Math.floor(minute / 1440) % 7]}) ${String(Math.floor(minute % 1440 / 60)).padStart(2, '0')}:${String(minute % 60).padStart(2, '0')}`;
export function Reveal({ title, text, children, info, preview = true }: {
    info?: ReactNode;
    title: string;
    text?: string;
    children?: ReactNode;
    preview?: boolean;
}) { const [expanded,setExpanded]=useState(false); return <details className="inspect-reveal" onToggle={e=>setExpanded(e.currentTarget.open)}><summary><span className="inspect-title">{title}</span>{info && <span className="muted small">{info}</span>}{preview && text && <span className="inspect-preview">{brief(text)}</span>}</summary>{expanded&&<div className="inspect-detail">{text && <Markdown text={text}/>}{children}</div>}</details>; }
function Items({ items }: {
    items: ReactNode[];
}) { return <>{items.slice(0, 5)}{items.length > 5 && <details className="inspect-more"><summary>Ещё {items.length - 5}</summary>{items.slice(5)}</details>}</>; }
function Empty({ children }: {
    children: ReactNode;
}) { return <p className="muted small">{children}</p>; }
function facts(s: State): WorldFact[] { return s.world?.facts ? Object.values(s.world.facts) : (s.facts || []).map((f, i) => ({ id: String(i), text: f.text, secret: false, character_ids: f.known_by, evidence: [] })); }
function FactRows({ state, values }: {
    state: State;
    values: WorldFact[];
}) { const knowledge = Object.values(state.world?.knowledge || {}); return values.length ? <Items items={values.map(f => { const known = knowledge.filter(k => k.fact_id === f.id && k.status === 'known').map(k => k.actor_id); const suspected = knowledge.filter(k => k.fact_id === f.id && k.status === 'suspected').map(k => k.actor_id); return <Reveal key={f.id} info={f.secret ? `Знают: ${names(state, known)} · Подозревают: ${names(state, suspected)}` : undefined} title={brief(f.text, 100)} text={f.text} preview={false}><p className="small">Знают: {names(state, state.world?.knowledge ? known : f.character_ids)}</p><p className="small">Подозревают: {names(state, suspected)}</p>{!!f.evidence?.length && <Reveal title="Основания" text={f.evidence.join('\n\n')} preview={false}/>}</Reveal>; })}/> : <Empty>Пока нет записанных фактов.</Empty>; }
export function SceneOverview({ state, meta }: {
    state: State;
    meta?: Scene;
}) { return <div className="scene-overview"><dl className="inspect-kv"><dt>Время</dt><dd>{meta?.time || state.world_clock?.last_event_time || 'Не указано'}</dd><dt>Место</dt><dd>{meta?.location || 'Не указано'}</dd><dt>Рядом</dt><dd>{names(state, meta?.present_ids || [])}</dd></dl><Reveal title="Текущая ситуация" text={state.scene}/></div>; }
export function WorldView({ state, meta }: {
    state: State;
    meta?: Scene;
}) { return <div className="inspector-content"><SceneOverview state={state} meta={meta}/><h3>Места</h3><Items items={state.locations.map((l, i) => <Reveal key={i} title={l.name} text={l.text}/>)}/><h3>Факты мира</h3><FactRows state={state} values={facts(state).filter(f => !f.secret)}/></div>; }
export function RelationsView({ state, actor }: {
    state: State;
    actor?: string;
}) { const structured = Object.values(state.world?.relationships || {}); const rows = structured.map(r => ({ source: r.source_id, target: r.target_id, text: r.context, dimensions: r.dimensions, change: state.relationships.find(old => old.source_id === r.source_id && old.target_id === r.target_id)?.change })); for (const r of state.relationships) {
    if (!structured.some(x => x.source_id === r.source_id && (x.target_id === r.target_id || nameOf(state, x.target_id) === r.target_name)))
        rows.push({ source: r.source_id, target: r.target_id || r.target_name || 'Неизвестно', text: r.text, dimensions: {}, change: r.change });
} return <div className="inspector-content"><Items items={rows.filter(r => !actor || r.source === actor || r.target === actor).map((r, i) => <Reveal key={i} info={Object.entries(r.dimensions).map(([k, v]) => `${k}: ${typeof v === 'number' ? v : v.direction === 'up' ? '↑' : v.direction === 'down' ? '↓' : '→'}`).join(' · ')} title={`${nameOf(state, r.source)} → ${nameOf(state, r.target)}`} text={r.text}><div className="inspect-chips">{Object.entries(r.dimensions).map(([key, value]) => <span className="pill" key={key}>{key}: {typeof value === 'number' ? value : <span className={value.direction === 'up' ? 'positive' : value.direction === 'down' ? 'negative' : ''}>{value.direction === 'up' ? '↑' : value.direction === 'down' ? '↓' : '→'} {value.reason}</span>}</span>)}</div>{r.change && <p className={r.change.direction === 'up' ? 'positive' : 'negative'}>{r.change.direction === 'up' ? '↑' : '↓'} {r.change.reason}</p>}</Reveal>)}/>{!rows.length && <Empty>Отношения пока не записаны.</Empty>}</div>; }
export function CharacterView({ state, card, save, refresh }: {
    save?:Save|null;
    refresh?:()=>void;
    state: State;
    card: Character;
}) { const current = state.world?.characters[card.id]; const main = state.protagonist_id || state.characters.find(c => c.is_player)?.id; const actor = state.controlled_actor_id === undefined ? main : state.controlled_actor_id; const knowledge = Object.values(state.world?.knowledge || {}).filter(k => k.actor_id === card.id && k.status !== 'unknown'); const excluded = ['Место', 'Время', 'Сейчас', 'Чего хочет', 'Намерения', 'Обязательства']; return <div className="inspector-content character-profile"><h2>{card.name}</h2><div className="inspect-chips">{card.id === main && <span className="pill">Основной ГГ</span>}{card.id === actor && <span className="pill">Под управлением</span>}{current?.emotion && <span className="pill">{current.emotion}</span>}</div><p className="character-lead">{brief(card.fields['Статус'] || 'Роль не указана', 100)}</p><dl className="inspect-kv"><dt>Где</dt><dd>{current?.location || card.fields['Место'] || 'Неизвестно'}</dd></dl><Reveal title="Сейчас" text={current?.situation || card.fields['Сейчас']}><p>Последняя точка: {current?.minute != null ? stamp(current.minute) : card.fields['Время'] || 'Не указана'}</p></Reveal>{Object.entries(card.fields).filter(([k]) => !excluded.includes(k) && !k.startsWith('Отношение к ')).map(([k, v]) => <Reveal key={k} title={k} text={v} preview={false}/>)}<Reveal title="Цели, намерения и обязательства" preview={false}><p className="muted small">Сведения ведущего; могут быть неизвестны другим персонажам.</p>{save&&refresh&&card.id===actor?<MotivationEditor key={`${save.id}-${card.id}`} save={save} card={card} refresh={refresh}/>:<><Reveal title="Цель" text={current?.short_goal || card.fields['Чего хочет']} preview={false}/><Reveal title="Намерения" text={current?.intentions?.join('\n\n') || card.fields['Намерения']} preview={false}/></>}<Reveal title="Обязательства" text={current?.obligations?.join('\n\n') || card.fields['Обязательства']} preview={false}/></Reveal><Reveal title={`Знания и подозрения · ${knowledge.length}`} preview={false}>{knowledge.map((k, i) => <Reveal key={i} title={k.status === 'known' ? 'Знает' : 'Подозревает'} text={state.world?.facts?.[k.fact_id]?.text || k.fact_id}/>)}</Reveal><Reveal title="Отношения" preview={false}>{save&&refresh&&card.id===actor?<RelationshipEditor key={`${save.id}-${card.id}`} save={save} card={card} refresh={refresh}/>:<RelationsView state={state} actor={card.id}/>}</Reveal><Reveal title="Все исходные поля карточки" preview={false}>{Object.entries(card.fields).map(([k, v]) => <Reveal key={k} title={k} text={v} preview={false}/>)}</Reveal></div>; }
export function SecretsView({ state }: {
    state: State;
}) { return <div className="inspector-content"><p className="eyebrow">Сведения ведущего · спойлеры</p><FactRows state={state} values={facts(state).filter(f => f.secret)}/><Reveal title="Исходные тайны и знания мира" text={state.sections.knowledge} preview={false}/></div>; }
export function ThreadsView({ state }: {
    state: State;
}) { const rows = state.world?.threads ? Object.values(state.world.threads) : (state.plans || []).map((p, i) => ({ id: String(i), description: p.text, state: p.text, status: p.status === 'open' ? 'active' : p.status === 'done' ? 'resolved' : p.status, character_ids: [], relevance: 0 })); const list = (active: boolean) => <Items items={rows.filter(t => ['active', 'developing'].includes(t.status) === active).sort((a, b) => b.relevance - a.relevance).map(t => <Reveal key={t.id} title={brief(t.description, 100)} text={t.state}><p className="small">{{ active: 'Активная', developing: 'Развивается', dormant: 'На паузе', resolved: 'Завершена', cancelled: 'Отменена' }[t.status] || t.status} · {names(state, t.character_ids)}</p>{t.description !== t.state && <Markdown text={t.description}/>}</Reveal>)}/>; return <div className="inspector-content"><h3>Активные линии</h3>{list(true)}{!rows.some(t => ['active', 'developing'].includes(t.status)) && <Empty>Активных линий пока нет.</Empty>}<details className="inspect-more"><summary>На паузе и завершённые</summary>{list(false)}</details><Reveal title="Исходные сюжетные заметки" text={state.story_notes} preview={false}/></div>; }
export function MemoryView({ state }: {
    state: State;
}) { const [scope, setScope] = useState('player'); const actor = state.controlled_actor_id === undefined ? state.protagonist_id || state.characters.find(c => c.is_player)?.id : state.controlled_actor_id; const knowledge = Object.values(state.world?.knowledge || {}).filter(k => k.actor_id === actor && k.status !== 'unknown'); const events = state.world?.events ? Object.values(state.world.events).filter(e => scope === 'player' ? e.player_observed : e.witnesses.includes(actor || '') || knowledge.some(k => k.status === 'known' && k.source_event_id === e.id)).sort((a, b) => (b.minute ?? -1) - (a.minute ?? -1) || b.source_sequence - a.source_sequence) : (state.events || []).filter(e=>scope==='player'||e.character_ids.includes(actor||'')).slice().reverse().map((e, i) => ({ id: String(i), text: e.text, participants: e.character_ids, minute: null, source_sequence: e.turn })); return <div className="inspector-content"><h3>Важные факты</h3><FactRows state={state} values={facts(state).filter(f => !f.secret)}/><h3>События</h3><label className="small">Показать<select aria-label="Видимость событий" value={scope} onChange={e => setScope(e.target.value)}><option value="player">Известно игроку</option><option value="actor" disabled={!actor}>Известно персонажу</option></select></label><Items items={events.map(e => <Reveal key={e.id} title={brief(e.text, 100)} text={e.text} preview={false}><p className="small">{stamp(e.minute)} · Ход {e.source_sequence}</p><p className="small">{names(state, e.participants)}</p></Reveal>)}/>{!events.length && <Empty>Событий пока нет.</Empty>}<h3>Знания текущего персонажа</h3>{actor ? <Items items={knowledge.map((k, i) => <Reveal key={i} title={k.status === 'known' ? 'Знает' : 'Подозревает'} text={state.world?.facts?.[k.fact_id]?.text || k.fact_id}/>)}/> : <Empty>Сейчас камера наблюдает мир без управляемого персонажа.</Empty>}<Reveal title="Исходная выжимка" preview={false}><h4>Объективная память ведущего</h4><Markdown text={state.memory?.summary || 'Память ещё не сжималась.'}/>{Object.entries(state.memory?.per_actor || {}).map(([id, m]) => <Reveal key={id} title={nameOf(state, id)} text={m.summary} preview={false}/>)}</Reveal></div>; }
