import {useEffect, useState} from 'react';
import {toast} from 'sonner';
import {api,download} from './api';
import {useJob} from './hooks';
import {active,type Job,type Preferences,type Workspace} from './types';
import {Preparation} from './Preparation';
import {Button} from './components/ui/button';
import {Input} from './components/ui/input';
import {Textarea} from './components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './components/ui/dialog';
import {Markdown} from './Markdown';

type Item=Record<string,unknown>;
type DraftState={campaign:Item;characters:(Item&{id:string;name:string;fields:Record<string,string>})[];locations:(Item&{id:string;name:string})[];world:Record<string,Record<string,Item>>;protagonist_id:string;controlled_actor_id:string;camera:{scene_id:string};world_clock:{minute:number}};
type Draft={id:string;name:string;revision:number;version_id:number|null;state:DraftState|null;validation:{errors:string[];warnings:string[]};import_warnings:string[];source_text:string;history:{id:number;reason:string;created_at:string}[];job:Job|null};
type Target={kind:string;id:string;field:string;value:unknown;label:string};
const labels:Record<string,string>={title:'Название',setting:'Обстановка',era:'Эпоха',genre:'Жанр',tone:'Тон',description:'Описание',rules:'Правила повествования',name:'Имя / название',aliases:'Другие имена',location:'Местоположение',situation:'Сейчас',goals:'Цели',intentions:'Намерения',emotion:'Эмоциональное состояние',obligations:'Обязательства',source_id:'От кого',target_id:'К кому',context:'Динамика отношений',dimensions:'Показатели отношений',text:'Описание',secret:'Секрет',character_ids:'Связанные персонажи',evidence:'Основания',actor_id:'Кто знает',fact_id:'Факт',status:'Статус',source_event_id:'Источник знания',state:'Текущее развитие',relevance:'Значимость',participants:'Участники',start_minute:'Начало · минуты недели',end_minute:'Конец · минуты недели',protagonist_id:'Основной герой',controlled_actor_id:'Управляемый персонаж',scene_id:'Стартовая сцена',minute:'Игровое время · минуты недели',witnesses:'Свидетели',fact_ids:'Факты',player_observed:'Известно игроку'};
const fields:Record<string,string[]>={campaign:['title','setting','era','genre','tone','description','rules'],actor:['location','situation','goals','intentions','emotion','obligations'],relationship:['source_id','target_id','context','dimensions'],location:['name','text'],fact:['text','secret','character_ids','evidence'],knowledge:['actor_id','fact_id','status','source_event_id'],thread:['description','state','status','character_ids','relevance'],scene:['location','participants','text','start_minute','end_minute','status'],event:['text','participants','witnesses','minute','fact_ids','player_observed'],start:['protagonist_id','controlled_actor_id','scene_id','minute']};
const groups=[['Персонажи','character','characters'],['Отношения','relationship','relationships'],['Места','location','locations'],['Факты и тайны','fact','facts'],['Знания персонажей','knowledge','knowledge'],['Сюжетные линии','thread','threads'],['Сцены','scene','scenes'],['События','event','events']];

export function WorldWorkshop({prefs,apiKey,onWorld,onGame}:{prefs:Preferences;apiKey:string;onWorld:(id:number)=>void;onGame:(world:number,save:number)=>void}){
 const [mode,setMode]=useState('quick');const [id,setId]=useState(localStorage.getItem('draftWorkspace')||'');
 const [list,setList]=useState<{id:string;name:string}[]>([]);const [draft,setDraft]=useState<Draft|null>(null);
 const [author,setAuthor]=useState(false);const [authorAsk,setAuthorAsk]=useState(false);const [text,setText]=useState('');const [name,setName]=useState('Новая история');const [useIdea,setUseIdea]=useState(false);
 const [busy,setBusy]=useState(false);const [edit,setEdit]=useState<Target|null>(null);const [value,setValue]=useState<unknown>('');const [instruction,setInstruction]=useState('');const [ack,setAck]=useState(false);const [confirmStart,setConfirmStart]=useState(false);
 const [related,setRelated]=useState<{kind:string;id:string}[]>([]);
 const [removal,setRemoval]=useState<{kind:string;id:string;deps:{kind:string;id:string}[]}|null>(null);
 const refresh=()=>{if(id)void api<Draft>(`/workspaces/${id}/draft?author=${author}`).then(setDraft).catch(e=>toast.error(e.message))};
 useEffect(()=>{void api<typeof list>('/workspaces').then(setList).catch(e=>toast.error(e.message))},[]);
 useEffect(()=>{setDraft(null);if(id){localStorage.setItem('draftWorkspace',id);const controller=new AbortController();void api<Draft>(`/workspaces/${id}/draft?author=${author}`,undefined,'GET',controller.signal).then(setDraft).catch(e=>{if(!controller.signal.aborted)toast.error(e.message)});return()=>controller.abort()}},[id,author]);
 const {job,reconnecting}=useJob(draft?.job,refresh);const locked=busy||active(job);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const change=(body:Item)=>run(async()=>{await api(`/workspaces/${id}/draft`,{revision:draft?.revision,...body},'PATCH');refresh()});
 const generate=(body:Item)=>run(async()=>{const j=await api<Job>(`/workspaces/${id}/draft/generate`,{revision:draft?.revision,config:prefs.summary,api_key:apiKey,...body});setDraft(d=>d?{...d,job:j}:d);setEdit(null)});
 const openEdit=(target:Target)=>{setEdit(target);setValue(target.value??'');setInstruction('');setAck(false)};
 const state=draft?.state;
 const characters=state?.characters||[];
 const options=(field:string):[string,string][]|null=>{
  if(['protagonist_id','controlled_actor_id','source_id','target_id','actor_id','character_ids','participants','witnesses'].includes(field))return characters.map(c=>[c.id,c.name]);
  const group=field==='scene_id'?'scenes':field==='fact_id'||field==='fact_ids'?'facts':field==='source_event_id'?'events':null;
  if(group)return Object.entries(state?.world[group]||{}).map(([k,v])=>[k,String(v.text||v.location||k)]);
  if(field==='status')return (edit?.kind==='knowledge'?['known','suspected','unknown']:edit?.kind==='thread'?['active','developing','dormant','resolved']:['active','closed']).map(x=>[x,x]);
  return null;
 };
 const printable=(field:string,v:unknown):string=>{const opts=options(field);if(Array.isArray(v))return v.map(x=>opts?.find(([k])=>k===x)?.[1]||String(x)).join(' · ');if(typeof v==='boolean')return v?'Да':'Нет';if(v&&typeof v==='object')return Object.entries(v).map(([k,x])=>`${k}: ${x}`).join(' · ');return opts?.find(([k])=>k===v)?.[1]||String(v??'Не указано')};
 const row=(kind:string,eid:string,field:string,v:unknown)=> <div className="draft-field" key={field}><div className="draft-field-heading"><span>{labels[field]||field.replace('fields.','')}</span>{author&&<Button variant="ghost" size="sm" disabled={locked} aria-label={`Изменить ${labels[field]||field}`} onClick={()=>openEdit({kind,id:eid,field,value:v,label:labels[field]||field.replace('fields.','')})}>Изменить</Button>}</div><details><summary>{printable(field,v)||'Не указано'}</summary><Markdown text={printable(field,v)}/></details></div>;
 const entity=(kind:string,eid:string,item:Item)=> <div className="draft-entity" key={eid}>
 {kind==='character'?<>{row(kind,eid,'name',item.name)}{row(kind,eid,'aliases',item.aliases||[])}{Object.entries(item.fields as Record<string,string>).filter(([k])=>!['Сейчас','Чего хочет','Намерения'].includes(k)).map(([k,v])=>row(kind,eid,'fields.'+k,v))}<details><summary>Состояние, цели и намерения</summary>{fields.actor.map(f=>row('actor',eid,f,state?.world.characters[eid]?.[f]??(['goals','intentions','obligations'].includes(f)?[]:'')))}</details></>:fields[kind].map(f=>row(kind,eid,f,item[f]??(['character_ids','participants','witnesses','fact_ids','evidence'].includes(f)?[]:'')))}
 {author&&<div className="actions">{kind==='character'&&<Button variant="outline" disabled={locked} onClick={()=>{setEdit({kind,id:eid,field:'__character',value:'',label:'Перегенерировать персонажа целиком'});setInstruction('');setAck(false);setRelated([]);void api<{kind:string;id:string}[]>(`/workspaces/${id}/draft/dependencies?kind=character&entity_id=${eid}`).then(setRelated).catch(e=>toast.error(e.message))}}>Новая версия персонажа</Button>}<Button variant="ghost" disabled={locked} onClick={()=>void run(async()=>{const deps=await api<{kind:string;id:string}[]>(`/workspaces/${id}/draft/dependencies?kind=${kind}&entity_id=${eid}`);setRemoval({kind,id:eid,deps})})}>Удалить</Button></div>}
 </div>;
 if(mode==='scenario')return <><Button className="workshop-back" variant="ghost" onClick={()=>setMode('quick')}>← Генератор мира</Button><Preparation prefs={prefs} apiKey={apiKey} onWorld={onWorld} onDraft={wid=>{setId(wid);setUseIdea(true);setMode('quick')}}/></>;
 return <main className="preparation world-workshop"><p className="eyebrow">Мастерская историй</p><h1>Мир начинается с замысла</h1><p className="muted">Создай основу, проверь детали и начни историю.</p>
 <div className="actions"><Button variant={mode==='quick'?'default':'outline'} onClick={()=>setMode('quick')}>Из идеи</Button><Button variant="outline" onClick={()=>setMode('scenario')}>Со Сценаристом</Button><Button variant={mode==='import'?'default':'outline'} onClick={()=>setMode('import')}>Импорт мира</Button></div>
 <div className="workspace-bar"><select aria-label="Черновик мира" value={id} onChange={e=>{setId(e.target.value);setAuthor(false);setUseIdea(false)}}><option value="">Выбрать черновик</option>{list.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><Input aria-label="Название черновика" value={name} onChange={e=>setName(e.target.value)}/><Button disabled={busy||!name.trim()} onClick={()=>void run(async()=>{const w=await api<Workspace>('/workspaces',{name});setList(xs=>[w,...xs]);setId(w.id);setAuthor(false)})}>Новый черновик</Button></div>
 {draft&&<><section className="document"><h2>{mode==='import'?'Импорт выжимки':'Какую историю хочется прожить?'}</h2>{mode==='import'&&<Input type="file" accept=".md,.txt" aria-label="Файл мира" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(setText)}}/>}<Textarea value={text} onChange={e=>setText(e.target.value)} aria-label="Описание мира или текст импорта" placeholder={mode==='import'?'Вставь готовую выжимку или экспорт мира':'Опиши персонажей, отношения, место и начало истории. Подробные требования можно писать обычным текстом.'}/>{mode==='quick'&&<label><input type="checkbox" checked={useIdea} onChange={e=>setUseIdea(e.target.checked)}/> Использовать сценарий этого черновика</label>}<Button disabled={locked||(!text.trim()&&!useIdea)} onClick={()=>mode==='import'?void run(async()=>{await api(`/workspaces/${id}/draft/import`,{text,revision:draft.revision});refresh()}):void generate({task:'world',text,use_idea:useIdea})}>{mode==='import'?'Разобрать в редактор':state?'Другой вариант мира':'Создать мир'}</Button></section>
 {active(job)&&<section role="status" className="document"><p>{reconnecting?'Восстанавливаем соединение…':'Генератор собирает мир…'}</p><p className="muted">Предыдущая версия останется доступна.</p><Button variant="outline" onClick={()=>void run(async()=>{await api(`/jobs/${job!.id}/stop`,{});refresh()})}>Остановить</Button></section>}{job?.error&&<p role="alert">{job.error}</p>}
 {state&&<><div className="actions"><h2>Редактор мира</h2><Button variant="outline" onClick={()=>author?setAuthor(false):setAuthorAsk(true)}>{author?'Перейти в вид игрока':'Открыть вид автора'}</Button></div><p className="muted">{author?'Вид автора: доступны скрытые факты и намерения. Изменения сохраняются как новые версии.':'Вид игрока: скрытая информация исключена сервером. Для редактирования открой вид автора.'}</p>
 <details className="draft-section" open={draft.validation.errors.length>0}><summary>Проверка мира · ошибок: {draft.validation.errors.length}, замечаний: {draft.validation.warnings.length+draft.import_warnings.length}</summary>{[...draft.validation.errors,...draft.validation.warnings,...draft.import_warnings].map((x,i)=><p key={i}>{x}</p>)}{!draft.validation.errors.length&&!draft.validation.warnings.length&&<p>Структура готова к запуску.</p>}</details>
 <details className="draft-section" open><summary>Кампания и правила</summary>{fields.campaign.map(f=>row('campaign','',f,state.campaign[f]||''))}</details>
 {groups.map(([title,kind,group])=><details key={kind} className="draft-section"><summary>{title} · {kind==='character'?characters.length:kind==='location'?state.locations.length:Object.keys(state.world[group]||{}).length}</summary>{(kind==='character'?characters:kind==='location'?state.locations:Object.entries(state.world[group]||{}).map(([key,v])=>({...v,id:key}))).map((item:Item)=><details key={String(item.id)} className="draft-card"><summary>{kind==='relationship'?`${characters.find(c=>c.id===item.source_id)?.name||'Не выбран'} → ${characters.find(c=>c.id===item.target_id)?.name||'Не выбран'}`:String(item.name||item.description||item.text||item.location||item.id)}</summary>{entity(kind,String(item.id),item)}</details>)}{author&&<Button variant="outline" disabled={locked} onClick={()=>void change({operation:'add',kind})}>+ Добавить</Button>}</details>)}
 {author&&<details className="draft-section"><summary>Старт игры и время</summary>{fields.start.map(f=>row('start','',f,f==='scene_id'?state.camera.scene_id:f==='minute'?state.world_clock.minute:state[f as 'protagonist_id'|'controlled_actor_id']))}<p className="muted">0 — понедельник 00:00; 1440 — вторник. Время хранится в единой шкале движка.</p></details>}
 <details className="draft-section"><summary>История версий · {draft.history.length}</summary>{draft.history.map((v,i)=><div className="actions" key={v.id}><span>Версия {draft.history.length-i} · {v.reason}</span>{author&&<Button disabled={locked||v.id===draft.version_id} variant="outline" onClick={()=>void change({operation:'restore',source_id:v.id})}>Восстановить</Button>}</div>)}</details>
 {author&&<><details className="draft-section"><summary>Исходный текст импорта</summary><Markdown text={draft.source_text||'Мир создан генератором.'}/></details><div className="actions">{['md','txt'].map(format=><Button key={format} variant="outline" onClick={()=>void run(async()=>{const response=await fetch(`/api/workspaces/${id}/draft/export?version_id=${draft.version_id}&format=${format}`);if(!response.ok)throw new Error('Не удалось экспортировать мир');download(await response.text(),`world.${format}`)})}>Экспорт .{format}</Button>)}</div></>}
 <Button disabled={locked||draft.validation.errors.length>0} onClick={()=>setConfirmStart(true)}>Подтвердить мир и начать игру</Button></>}
 </>}
 <Dialog open={authorAsk} onOpenChange={setAuthorAsk}><DialogContent><DialogHeader><DialogTitle>Открыть вид автора?</DialogTitle><DialogDescription>Ты увидишь тайны, неизвестные персонажам факты и скрытые намерения. Это может раскрыть будущие события.</DialogDescription></DialogHeader><Button onClick={()=>{setAuthorAsk(false);setAuthor(true)}}>Показать всё</Button></DialogContent></Dialog>
 <Dialog open={!!edit} onOpenChange={o=>{if(!o)setEdit(null)}}><DialogContent><DialogHeader><DialogTitle>{edit?.label}</DialogTitle><DialogDescription>Меняется только выбранное поле. Остальные сущности сохраняются.</DialogDescription></DialogHeader>{edit&&edit.field!=='__character'&&<>{options(edit.field)?Array.isArray(value)?<div className="draft-options">{options(edit.field)!.map(([k,n])=><label key={k}><input type="checkbox" checked={value.includes(k)} onChange={e=>setValue(e.target.checked?[...value,k]:value.filter(x=>x!==k))}/>{n}</label>)}</div>:<select aria-label={edit.label} value={String(value??'')} onChange={e=>setValue(e.target.value||null)}><option value="">Не указано</option>{options(edit.field)!.map(([k,n])=><option key={k} value={k}>{n}</option>)}</select>:typeof value==='boolean'?<label><input type="checkbox" checked={value} onChange={e=>setValue(e.target.checked)}/>Да</label>:typeof value==='number'?<Input type="number" aria-label={edit.label} value={value} onChange={e=>setValue(Number(e.target.value))}/>:value&&typeof value==='object'&&!Array.isArray(value)?<div>{['trust','affection','attraction','irritation','fear','jealousy','respect',...Object.keys(value)].filter((v,i,a)=>a.indexOf(v)===i).map(k=><label key={k}>{k}<Input type="number" value={String((value as Item)[k]??'')} onChange={e=>{const next={...value} as Item;if(e.target.value==='')delete next[k];else next[k]=Number(e.target.value);setValue(next)}}/></label>)}</div>:<Textarea aria-label={edit.label} value={Array.isArray(value)?value.join('\n'):String(value??'')} onChange={e=>setValue(Array.isArray(value)?e.target.value.split('\n'):e.target.value)}/>}<Button disabled={locked} onClick={()=>void run(async()=>{await api(`/workspaces/${id}/draft`,{revision:draft?.revision,operation:'patch',kind:edit.kind,entity_id:edit.id,field:edit.field,value,warnings_ack:ack},'PATCH');setEdit(null);refresh()})}>Сохранить поле</Button></>}
 {edit?.field==='__character'&&<div><p>Связанные записи останутся неизменными; проверь их после изменения биографии:</p>{related.map(d=><p key={d.kind+d.id}>{d.kind} · {d.id}</p>)}</div>}<Textarea aria-label="Указание генератору" placeholder="Как изменить? Например: сделать характер мягче, сохранив биографию." value={instruction} onChange={e=>setInstruction(e.target.value)}/><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> Изменить всё равно при семантических замечаниях</label><Button variant="outline" disabled={locked} onClick={()=>edit&&void generate({task:edit.field==='__character'?'character':'field',kind:edit.kind,entity_id:edit.id,field:edit.field,text:instruction,warnings_ack:ack})}>Перегенерировать {edit?.field==='__character'?'персонажа':'поле'}</Button></DialogContent></Dialog>
 <Dialog open={!!removal} onOpenChange={o=>{if(!o)setRemoval(null)}}><DialogContent><DialogHeader><DialogTitle>Удалить запись?</DialogTitle><DialogDescription>{removal?.deps.length?'Сначала измени связанные записи. Автоматически удалять их нельзя.':'Будет создана новая версия. Предыдущую можно восстановить из истории.'}</DialogDescription></DialogHeader>{removal?.deps.map(d=><p key={d.kind+d.id}>{d.kind} · {characters.find(c=>c.id===d.id)?.name||d.id}</p>)}<Button disabled={locked||!!removal?.deps.length} onClick={()=>void run(async()=>{await api(`/workspaces/${id}/draft`,{revision:draft?.revision,operation:'remove',kind:removal?.kind,entity_id:removal?.id},'PATCH');setRemoval(null);refresh()})}>Удалить</Button></DialogContent></Dialog>
 <Dialog open={confirmStart} onOpenChange={setConfirmStart}><DialogContent><DialogHeader><DialogTitle>Начать эту историю?</DialogTitle><DialogDescription>Будет сохранена текущая версия мира. Повторной генерации или разбора текста не будет.</DialogDescription></DialogHeader>{draft?.validation.warnings.map(x=><p key={x}>{x}</p>)}<Button disabled={locked} onClick={()=>void run(async()=>{const result=await api<{world:number;save:number}>(`/workspaces/${id}/draft/confirm`,{revision:draft?.revision,version_id:draft?.version_id});setConfirmStart(false);onGame(result.world,result.save)})}>Подтвердить и открыть игру</Button></DialogContent></Dialog>
 </main>;
}
