import {test,expect} from '@playwright/test';
import {nav} from './navigation';
test('edit motivation within character card and persist after reload',async({page,request})=>{
 const selection=await(await request.post('/test/seed')).json();
 await page.addInitScript(s=>localStorage.setItem('selection',JSON.stringify(s)),selection);
 await page.goto('/');await nav(page,'Мир');await page.locator('.panel-tabs').getByRole('button',{name:'Персонажи',exact:true}).click();
 const panel=page.locator('.inspector-dialog');
 await panel.getByText('Цели, намерения и обязательства',{exact:true}).click();
 await panel.getByRole('button',{name:'+ Добавить цель',exact:true}).click();
 const goalDialog=page.getByRole('dialog').filter({has:page.getByRole('heading',{name:'Цель персонажа',exact:true})});
 await goalDialog.getByLabel('Текст цели или намерения').fill('Найти старую карту');
 await goalDialog.getByRole('button',{name:'Сохранить',exact:true}).click();
 await expect(panel.locator('.motivation-editor')).toContainText('Найти старую карту');
 await panel.getByLabel('Действия с целью 2').click();await panel.getByRole('button',{name:'Редактировать',exact:true}).click();
 await goalDialog.getByLabel('Текст цели или намерения').fill('Изучить старую карту');
 await goalDialog.getByRole('button',{name:'Сохранить',exact:true}).click();
 await expect(panel.locator('.motivation-editor')).toContainText('Изучить старую карту');
 await panel.getByRole('button',{name:'+ Добавить намерение',exact:true}).click();
 const editor=page.getByRole('dialog').filter({has:page.getByRole('heading',{name:'Намерение персонажа',exact:true})});
 await editor.getByLabel('Текст цели или намерения').fill('Поговорить со смотрителем маяка');
 await editor.getByRole('button',{name:'Сохранить',exact:true}).click();
 await expect(editor).toHaveCount(0);await expect(panel.locator('.motivation-row')).toContainText(['Поговорить со смотрителем маяка']);
 await page.reload();await nav(page,'Мир');await page.locator('.panel-tabs').getByRole('button',{name:'Персонажи',exact:true}).click();await panel.getByText('Цели, намерения и обязательства',{exact:true}).click();
 await expect(panel.locator('.motivation-editor')).toContainText('Поговорить со смотрителем маяка');
 await panel.getByLabel('Действия с намерением 1').click();await panel.getByRole('button',{name:'Удалить',exact:true}).click();
 const confirm=page.getByRole('dialog').filter({has:page.getByRole('heading',{name:'Удалить запись?',exact:true})});
 await confirm.getByRole('button',{name:'Отмена',exact:true}).click();
 await expect(panel.locator('.motivation-editor')).toContainText('Поговорить со смотрителем маяка');
 await panel.getByLabel('Действия с намерением 1').click();await panel.getByRole('button',{name:'Удалить',exact:true}).click();
 await confirm.getByRole('button',{name:'Удалить',exact:true}).click();
 await expect(confirm).toHaveCount(0);await expect(panel.locator('.motivation-editor')).not.toContainText('Поговорить со смотрителем маяка');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
});
