import {nav,actor} from "./navigation";
import {test,expect} from '@playwright/test';
test('POV, backstage and prompt versions',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const selected=await (await request.post('/test/seed')).json();
 await page.addInitScript(s=>localStorage.setItem('selection',JSON.stringify(s)),selected);
 await page.goto('/');
 await page.getByRole('button',{name:'Начать игру',exact:true}).click();
 await expect(page.locator('.turn')).toHaveCount(1);
 await actor(page,'character_2','Персонаж 1');
 await expect(page.locator('.turn')).toHaveCount(2);
 await page.getByRole('button',{name:'Мир без ГГ',exact:true}).click();
 await expect(page.locator('.turn')).toHaveCount(3);
 await expect(page.locator('.turn').last()).toContainText('За кулисами');
 await expect(page.locator('.choices button')).toHaveCount(0);
 let save=await (await request.get(`/api/saves/${selected.save}`)).json();
 expect(save.state.controlled_actor_id).toBeNull();
 expect(save.state.camera.mode).toBe('observer');
 expect(save.state.facts.at(-1).known_by).toEqual(['character_3','character_4']);
 await page.locator('.background-exit').getByRole('button',{name:'Вернуться к Персонаж 0'}).click();
 await expect(page.locator('.turn')).toHaveCount(4);
 await expect(page.locator('.choices button')).toHaveCount(6);
 await page.reload();
 await nav(page,'Настройки');
 await page.getByText('Основные промпты и версии',{exact:true}).click();
 await page.getByRole('button',{name:'background_prompt.md',exact:true}).click();
 const versions=page.getByRole('dialog').last();
 await expect(versions).toContainText('История версий');
 await expect(versions.getByLabel('Содержимое версии')).toBeEnabled();
 const initial=await versions.locator('select option').count();
 const text=await versions.getByLabel('Содержимое версии').inputValue();
 await versions.getByLabel('Содержимое версии').fill(text+'\nПроверка версии.');
 await versions.getByRole('button',{name:'Сохранить новую версию'}).click();
 await expect(versions.locator('select option')).toHaveCount(initial+1);
 const old=await versions.locator('select option').last().getAttribute('value');
 await versions.locator('select').selectOption(old!);
 page.once('dialog',d=>d.accept());
 await versions.getByRole('button',{name:'Откатить к выбранной'}).click();
 await expect(versions.locator('select option')).toHaveCount(initial+2);
 expect(await versions.getByLabel('Содержимое версии').inputValue()).toBe(text);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
 expect(errors).toEqual([]);
});

test('scenario and summary deletion keeps restorable versions and saves',async({page,request})=>{
 const selected=await (await request.post('/test/seed')).json();
 const world=await (await request.get(`/api/worlds/${selected.world}`)).json();
 const w=await (await request.post('/api/workspaces',{data:{name:'Удаление и версии'}})).json();
 for(const [kind,content] of [['idea','Исходный сценарий'],['summary',world.source_md]]){
   const h=await (await request.get(`/api/documents/${kind}/${w.id}`)).json();
   await request.post(`/api/documents/${kind}/${w.id}`,{data:{content,expected_head:h.active_id}});
 }
 await page.addInitScript(id=>localStorage.setItem('workspace',id),w.id);
 await page.goto('/');
 await nav(page,'Создать');
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Удалить выжимку',exact:true}).click();
 await expect(page.getByRole('button',{name:'Удалить выжимку',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Версии выжимки'}).click();
 const dialog=page.getByRole('dialog');
 await expect(dialog.getByLabel('Содержимое версии')).toBeEnabled();
 const h=await (await request.get(`/api/documents/summary/${w.id}`)).json();
 const completed=h.versions.find((v:{content:string})=>v.content.length>0);
 await dialog.getByRole('combobox').selectOption(String(completed.id));
 page.once('dialog',d=>d.accept());
 await dialog.getByRole('button',{name:'Откатить к выбранной'}).click();
 await expect(dialog.locator('select option')).toHaveCount(h.versions.length+1);
 await dialog.getByRole('button',{name:'Закрыть',exact:true}).click();
 await expect(page.getByRole('button',{name:'Удалить выжимку',exact:true})).toBeVisible();
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Удалить сценарий',exact:true}).click();
 await page.getByText('Удалённые сценарии',{exact:true}).click();
 await page.getByRole('button',{name:'Обновить корзину'}).click();
 await page.getByRole('button',{name:'Восстановить',exact:true}).filter({visible:true}).last().click();
 await expect(page.getByRole('button',{name:'Удалить выжимку',exact:true})).toBeVisible();
 expect((await (await request.get(`/api/saves/${selected.save}`)).json()).world_id).toBe(selected.world);
});
