import {nav,diagnostics} from "./navigation";
import {test,expect} from "@playwright/test";
test("persistent key, thinking, memory, visible player actions, variants and accounting",async({page,request})=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 const selected=await (await request.post('/test/seed')).json();
 await page.addInitScript(s=>localStorage.setItem('selection',JSON.stringify(s)),selected);
 await page.goto('/');
 await nav(page,'Настройки');
 await page.getByLabel('Провайдер game').selectOption('deepseek');
 await page.getByLabel('API-ключ DeepSeek').fill('persisted-test-key');
 await page.getByLabel('Thinking game').selectOption('low');
 await page.getByRole('button',{name:'Сохранить настройки'}).click();
 await expect(page.getByRole('dialog')).toBeHidden();
 await page.reload();
 await page.getByRole('button',{name:'Начать игру',exact:true}).click();
 await expect(page.locator('.turn')).toHaveCount(1);
 await expect(page.locator('.choices button')).toHaveCount(6);
 await page.locator('.choices button').first().click();
 await expect(page.locator('.turn')).toHaveCount(2);
 await expect(page.locator('.turn').last().getByTestId('player-action')).toContainText('Действие 0: «Реплика 0»');
 await page.getByLabel('Своё действие или реплика').fill('Мой собственный выбор');
 await page.getByRole('button',{name:'Отправить действие',exact:true}).click();
 await expect(page.locator('.turn')).toHaveCount(3);
 await expect(page.locator('.turn').last().getByTestId('player-action')).toContainText('Мой собственный выбор');
 await page.locator('.turn').first().getByRole('button',{name:'Ещё вариант'}).scrollIntoViewIfNeeded();
 page.once('dialog',d=>d.accept());
 await page.locator('.turn').first().getByRole('button',{name:'Ещё вариант'}).click();
 await expect(page.locator('.turn')).toHaveCount(1);
 if(await page.locator('.mobile-variants').isVisible()){await expect(page.locator('.mobile-variants')).toContainText('2 / 2');await page.getByRole('button',{name:'Предыдущий вариант'}).click();await expect(page.locator('.mobile-variants')).toContainText('1 / 2')}else{await expect(page.getByText('Вариант 2 / 2')).toBeVisible();await page.locator('.variant-controls').getByRole('button',{name:'1',exact:true}).click();await expect(page.getByText('Вариант 1 / 2')).toBeVisible()}
 await diagnostics(page);
 await expect(page.getByRole('dialog')).toContainText('Cache');
 await expect(page.getByRole('dialog')).toContainText('low');
 await expect(page.getByRole('dialog')).toContainText('Текущая сцена');
 await page.getByRole('button',{name:'Показать архив откатов'}).click();
 await expect(page.getByRole('dialog')).toContainText('variant_switch');
 await page.getByRole('button',{name:'Закрыть',exact:true}).click();
 const acc=await (await request.get(`/api/saves/${selected.save}/accounting`)).json();
 expect(acc.game.input_tokens).toBeGreaterThan(0);
 expect(Number(acc.game.cost_usd)).toBeGreaterThan(0);
 expect(await (await request.get('/api/credentials')).json()).toEqual({deepseek:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);expect(overflow).toBe(false);
 expect(errors).toEqual([]);
});
